# Generated by Django 4.0.5 on 2022-06-23 14:11

from django.db import migrations, models
import onlinecourse.models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0003_course_tutorial_enrolled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to=onlinecourse.models.upload_to),
        ),
    ]
